//! Parity tests: the obfuscated Rust ladder MUST equal the original Dart
//! formula exactly. Any drift here is a game-balance bug.
//!
//! Reference values were generated by running the pre-port Dart code once
//! (see lib/game/difficulty.dart). Keep them pinned.

use rust_guard::math::*;

#[test]
fn multipliers_match_reference() {
    // Reference ladder from the original Dart `_rtp = 0.97`, 18-lane generator.
    let expected: [[f64; 18]; 4] = [
        // easy (base 0.94)
        [
            1.03, 1.1, 1.17, 1.25, 1.33, 1.43, 1.53, 1.63, 1.75, 1.88, 2.02, 2.17,
            2.33, 2.51, 2.71, 2.92, 3.16, 3.41,
        ],
        // medium (base 0.84)
        [
            1.15, 1.38, 1.64, 1.96, 2.34, 2.81, 3.36, 4.03, 4.84, 5.82, 7.0, 8.43, 10.2,
            12.3, 14.8, 17.9, 21.7, 26.3,
        ],
        // hard (base 0.72)
        [
            1.35, 1.87, 2.61, 3.64, 5.08, 7.09, 9.92, 13.9, 19.5, 27.4, 38.5, 54.2, 76.4,
            108.0, 152.0, 216.0, 305.0, 433.0,
        ],
        // hardcore (base 0.56)
        [
            1.73, 3.1, 5.55, 9.96, 17.9, 32.2, 58.1, 105.0, 190.0, 343.0, 623.0, 1100.0,
            2100.0, 3800.0, 6900.0, 13000.0, 23000.0, 42000.0,
        ],
    ];

    for diff in 0..4u32 {
        let mut out = [0f64; 18];
        let n = multipliers(diff, &mut out);
        assert_eq!(n, 18, "diff {diff} count");
        for i in 0..18 {
            let got = out[i];
            let want = expected[diff as usize][i];
            // Tier-rounded ladder — compare directly.
            assert_eq!(
                got, want,
                "diff {diff} lane {i}: got {got} want {want}"
            );
        }
    }
}

#[test]
fn survival_edge_cases() {
    // Lane 0 is always a guaranteed survival (matches Dart invariant).
    assert_eq!(decide(0, 0, u64::MAX), 1);
    assert_eq!(decide(3, 0, 0), 1);
    // OOB lanes die (defensive).
    assert_eq!(decide(0, 999, 0), 0);
}

#[test]
fn cashout_matches_table() {
    let mut tab = [0f64; 18];
    multipliers(1, &mut tab); // medium
    // Bet 10.00 → 1000 cents.
    for lane in 0..18 {
        let got = cashout_cents(1, lane as u32, 1000);
        let want = (1000.0 * tab[lane]).round() as u64;
        assert_eq!(got, want, "lane {lane}");
    }
}

#[test]
fn round_mult_tiers() {
    assert_eq!(round_mult(1.0349), 1.03);
    assert_eq!(round_mult(99.44), 99.4);
    assert_eq!(round_mult(234.6), 235.0);
    assert_eq!(round_mult(12345.0), 12000.0);
}
