// Build-time string sealer for rust_guard.
//
// Reads a compiled-in table of (id, plaintext) pairs, encrypts each with a
// per-id keystream derived from `RG_BUILD_SEED` (fresh per build), and emits
// `$OUT_DIR/sealed_blob.rs` with the ciphertexts, nonces and per-id seeds.
//
// The plaintexts never appear in the final `.so`: only the ciphertext bytes
// are embedded. A clean `strings` dump should show nothing meaningful.

use std::env;
use std::fs;
use std::path::PathBuf;

fn ks(seed: u64, nonce: &[u8; 16], len: usize) -> Vec<u8> {
    // Keystream = SplitMix64 bytes seeded by (seed ^ nonce halves).
    let mut state: u64 = seed
        ^ u64::from_le_bytes(nonce[..8].try_into().unwrap())
        ^ u64::from_le_bytes(nonce[8..].try_into().unwrap()).rotate_left(13);
    let mut out = Vec::with_capacity(len);
    for _ in 0..len {
        state = state.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = state;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^= z >> 31;
        out.push(z as u8);
    }
    out
}

fn seal(id: u32, plain: &[u8], build_seed: u64) -> (u64, [u8; 16], Vec<u8>) {
    let per_id_seed = build_seed
        .wrapping_mul(0x9E37_79B9_7F4A_7C15)
        ^ (id as u64).wrapping_mul(0xBF58_476D_1CE4_E5B9);
    let nonce_u = per_id_seed.rotate_right(5) ^ 0xDEAD_BEEF_CAFE_BABE;
    let mut nonce = [0u8; 16];
    nonce[..8].copy_from_slice(&nonce_u.to_le_bytes());
    nonce[8..].copy_from_slice(
        &nonce_u
            .wrapping_add(id as u64)
            .rotate_left(21)
            .to_le_bytes(),
    );
    let k = ks(per_id_seed, &nonce, plain.len());
    let ct: Vec<u8> = plain.iter().zip(k.iter()).map(|(a, b)| a ^ b).collect();
    (per_id_seed, nonce, ct)
}

fn main() {
    // Build seed: taken from env or a stable default (fine for reproducible
    // builds — if you want per-release re-fingerprinting, bump the env).
    let seed_env = env::var("RG_BUILD_SEED").unwrap_or_default();
    let seed: u64 = if seed_env.is_empty() {
        0xA7E5_B91D_43CC_61F2
    } else if let Some(rest) = seed_env.strip_prefix("0x") {
        u64::from_str_radix(rest, 16).unwrap_or(0xA7E5_B91D_43CC_61F2)
    } else {
        seed_env
            .parse::<u64>()
            .unwrap_or(0xA7E5_B91D_43CC_61F2)
    };

    // (id, plaintext) — these are the only strings that live anywhere in the
    // app. Nothing beyond this table is embedded in the Flutter Dart source.
    //
    // IDs used by Dart (see lib/prism/sealed_bytes.dart):
    //   1  privacy policy URL
    //   2  support URL
    //   3  default user-agent (used by the relay client; shaped per-device)
    //   4  edge/sync endpoint (relay)
    //   5  envelope field name — schema
    //   6  envelope field name — nonce
    //   7  envelope field name — payload
    //   8  envelope field name — tag
    //   9  envelope schema revision (ascii decimal)
    //  10  relay HMAC/keystream secret (used by in-Rust envelope packer only)
    //  11  app bundle id
    //  12  app display name
    //
    // ⚠️ Nothing here is ever decrypted on the Flutter side without going
    // through rg_fetch(id). Dart stays clean of plaintext.
    let items: &[(u32, &[u8])] = &[
        (1, b"https://chickenrushs.com/privacy-policy"),
        (2, b"https://chickenrushs.com/support"),
        (
            3,
            b"Mozilla/5.0 (Linux; Android 16; SM-A556E) AppleWebKit/537.36 \
              (KHTML, like Gecko) Chrome/149.0.7745.90 Mobile Safari/537.36",
        ),
        (4, b"https://chickenrushs.com/edge/sync"),
        (5, b"a"),
        (6, b"m"),
        (7, b"w"),
        (8, b"e"),
        (9, b"11"),
        (10, b"0RxIjw9dV5u0gEGNt7R_FW7mVCb1czar0lHZi8kxqtY"),
        (11, b"com.crimsonpixel.arcade"),
        (12, b"Chicken Rush"),
    ];

    let mut out = String::new();
    out.push_str("// GENERATED by build.rs — do not edit.\n");
    out.push_str(&format!(
        "pub const BUILD_SEED: u64 = 0x{:016x}u64;\n",
        seed
    ));
    out.push_str(
        "pub struct Sealed { pub id: u32, pub seed: u64, pub nonce: [u8;16], pub ct: &'static [u8] }\n",
    );
    out.push_str("pub static SEALED: &[Sealed] = &[\n");
    for (id, plain) in items {
        let (per_id_seed, nonce, ct) = seal(*id, plain, seed);
        out.push_str(&format!(
            "  Sealed {{ id: {}, seed: 0x{:016x}u64, nonce: [",
            id, per_id_seed
        ));
        for (i, b) in nonce.iter().enumerate() {
            if i > 0 {
                out.push(',');
            }
            out.push_str(&format!("0x{:02x}", b));
        }
        out.push_str("], ct: &[");
        for (i, b) in ct.iter().enumerate() {
            if i > 0 {
                out.push(',');
            }
            out.push_str(&format!("0x{:02x}", b));
        }
        out.push_str("] },\n");
    }
    out.push_str("];\n");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    fs::write(out_dir.join("sealed_blob.rs"), out).unwrap();
    println!("cargo:rerun-if-env-changed=RG_BUILD_SEED");
    println!("cargo:rerun-if-changed=build.rs");
}
