[package]
name = "rust_guard"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[lib]
name = "rust_guard"
crate-type = ["cdylib", "staticlib", "rlib"]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"
overflow-checks = false
debug = false
incremental = false

[profile.release.package."*"]
opt-level = 3
